font:
  - file: "gfonts://Roboto"
    id: font1
    size: 14
  - file: "gfonts://Roboto"
    id: font2
    size: 24
  - file: "gfonts://Roboto"
    id: font3
    size: 40

globals:
  - id: auto_page_cycle
    type: bool
    initial_value: 'true'

# Logic to rotate pages automatically
interval:
  - interval: 10s
    then:
      - if:
          condition:
            lambda: |-
              return id(auto_page_cycle) && id(main_backlight).remote_values.is_on();
          then:
            - if:
                condition:
                  lambda: 'return lv_disp_get_scr_act(nullptr) == id(page_home).obj;'
                then:
                  - lvgl.page.show: page_hass
                else:
                  - if:
                      condition:
                        lambda: 'return lv_disp_get_scr_act(nullptr) == id(page_hass).obj;'
                      then:
                        - lvgl.page.show: page_skynas
                      else:
                        - if:
                            condition:
                              lambda: 'return lv_disp_get_scr_act(nullptr) == id(page_skynas).obj;'
                            then:
                              - lvgl.page.show: page_rack
                            else:
                              - if:
                                  condition:
                                    lambda:  'return lv_disp_get_scr_act(nullptr) == id(page_rack).obj;'
                                  then:
                                    - lvgl.page.show: page_fan
                                  else:
                                    - lvgl.page.show: page_home

script:
  - id: reset_sleep_timer
    mode: restart
    then:
      - delay: 60s
      # - light.turn_off: main_backlight
light:
  - platform: monochromatic
    output: backlight_out
    name: "Display Backlight"
    id: main_backlight

fan:
  - platform: speed
    output: fan_pwm
    id: rack_fans
    speed_count: 100
    on_speed_set:
      then:
        - lvgl.slider.update:
            id: fan_slider
            value: !lambda "return (int)x;"
        - lvgl.label.update:
            id: fan_speed_text
            text: !lambda |-
              static std::string fan_buf;
              fan_buf = "SPEED: " + std::to_string((int)x) + "%";
              return fan_buf.c_str();


output:
  - platform: ledc
    pin: GPIO21
    id: backlight_out
  - platform: ledc
    pin: GPIO27
    id: fan_pwm
    frequency: 25000Hz

esphome:
  name: esp32-touch-display
  friendly_name: ESP32 Touch Display
  on_boot:
    priority: -100
    then:
      - light.turn_on: main_backlight

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "display"
    password: !secret wifi_password

captive_portal:

spi:
  - id: bus_tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: bus_touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

display:
  - platform: ili9xxx
    id: my_display
    model: ILI9341
    spi_id: bus_tft
    data_rate: 40MHz
    cs_pin: GPIO15
    dc_pin: GPIO2
    invert_colors: false
    rotation: 270
    color_palette: NONE

touchscreen:
  platform: xpt2046
  id: my_touch
  display: my_display
  spi_id: bus_touch
  cs_pin: GPIO33
  interrupt_pin: GPIO36
  update_interval: 50ms
  threshold: 600
  calibration:
    x_min: 300
    x_max: 3850
    y_min: 350
    y_max: 3850
  transform:
    swap_xy: true
    mirror_x: true
    mirror_y: true
  on_touch:
    then:
      - if:
          condition:
            light.is_off: main_backlight
          then:
            - light.turn_on: main_backlight
          else:
            - script.execute: reset_sleep_timer
            
lvgl:
  update_interval: 1s
      
  top_layer:
    widgets:
      # Previous Page Button (Bottom Left)
      - button:
          id: btn_prev
          x: 5
          y: 205
          width: 40
          height: 30
          bg_color: 0x333333
          radius: 5
          widgets:
            - label: { text: "<", align: CENTER, text_font: font2 }
          on_click:
            then:
              - script.execute: reset_sleep_timer
              - lambda: |-
                  auto* active = lv_disp_get_scr_act(nullptr);
                  if (active == id(page_home).obj) lv_disp_load_scr(id(page_fan).obj);
                  else if (active == id(page_hass).obj) lv_disp_load_scr(id(page_home).obj);
                  else if (active == id(page_skynas).obj) lv_disp_load_scr(id(page_hass).obj);
                  else if (active == id(page_rack).obj) lv_disp_load_scr(id(page_skynas).obj);
                  else if (active == id(page_fan).obj) lv_disp_load_scr(id(page_rack).obj);

      # Next Page Button (Bottom Right)
      - button:
          id: btn_next
          x: 275
          y: 205
          width: 40
          height: 30
          bg_color: 0x333333
          radius: 5
          widgets:
            - label: { text: ">", align: CENTER, text_font: font2 }
          on_click:
            then:
              - script.execute: reset_sleep_timer
              - lambda: |-
                  auto* active = lv_disp_get_scr_act(nullptr);
                  if (active == id(page_home).obj) lv_disp_load_scr(id(page_hass).obj);
                  else if (active == id(page_hass).obj) lv_disp_load_scr(id(page_skynas).obj);
                  else if (active == id(page_skynas).obj) lv_disp_load_scr(id(page_rack).obj);
                  else if (active == id(page_rack).obj) lv_disp_load_scr(id(page_fan).obj);
                  else if (active == id(page_fan).obj) lv_disp_load_scr(id(page_home).obj);
      - label:
          text: "Wifi:"
          x: 5
          y: 11
          text_font: font1
          text_color: 0xFFFFFF
      - obj:
          id: signal_container
          x: 45
          y: 8
          width: 40
          height: 30
          bg_opa: 0%  # Transparent background
          bg_color: 0x444444
          border_width: 0
          shadow_width: 0
          pad_all: 0
          widgets:
            # Bar 1 (Shortest)
            - obj:
                id: bar_1
                x: 0
                y: 12
                width: 5
                height: 5
                bg_opa: 0%
                border_width: 0
                shadow_width: 0
                bg_color: 0x444444 # Default "Off" color
            # Bar 2
            - obj:
                id: bar_2
                x: 8
                y: 8
                width: 5
                height: 9
                bg_opa: 0%
                border_width: 0
                shadow_width: 0
                bg_color: 0x444444
            # Bar 3
            - obj:
                id: bar_3
                x: 16
                y: 4
                width: 5
                height: 13
                bg_opa: 0%
                border_width: 0
                shadow_width: 0
                bg_color: 0x444444
            # Bar 4 (Tallest)
            - obj:
                id: bar_4
                x: 24
                y: 0
                width: 5
                height: 17
                bg_opa: 0%
                border_width: 0
                shadow_width: 0
                bg_color: 0x444444

      - button:
          id: pause_btn
          x: 275
          y: 5
          width: 40
          height: 30
          bg_color: 0x444444
          radius: 5
          widgets: 
            - label: 
                id: pause_icon
                text: "||"
                align: CENTER
          on_click:
            then:
              - lambda: 'id(auto_page_cycle) = !id(auto_page_cycle);'
              - if:
                  condition:
                    lambda: 'return id(auto_page_cycle);'
                  then:
                    - lvgl.label.update: { id: pause_icon, text: "||" }
                    - lvgl.widget.update: { id: pause_btn, bg_color: 0x444444 }
                  else:
                    - lvgl.label.update: { id: pause_icon, text: ">" }
                    - lvgl.widget.update: { id: pause_btn, bg_color: 0xFF5252 }

  pages:
    - id: page_home
      bg_color: 0x121212
      widgets:
        - label: { text: "STATUS DISPLAY", align: TOP_MID, y: 15, text_color: 0x2196F3 }
        - label: { text: "SkyNet", align: TOP_MID, y: 45, text_font: font3, text_color: 0xFFFFFF }
        - label: { id: uptime_label, align: CENTER, y: 55, text_font: font1, text_color: 0xFFFFFF }
            
    - id: page_hass
      bg_color: 0x121212
      widgets:
        - label: { text: "HOME ASSISTANT", align: TOP_MID, y: 15, text_color: 0x2196F3 }
        - arc: { id: ha_cpu_gauge, x: 40, y: 55, width: 90, height: 90, arc_color: 0xF3212D }
        - label: { id: ha_cpu_val_label, x: 68, y: 145, text: "--%", text_color: 0x2196F3 }
        - label: { text: "CPU USAGE", x: 55, y: 165, text_color: 0xAAAAAA, text_font: font1 }
        - arc: { id: ha_mem_gauge, x: 190, y: 55, width: 90, height: 90, arc_color: 0xF3212D }
        - label: { id: ha_mem_val_label, x: 215, y: 145, text: "--%", text_color: 0x2196F3 }
        - label: { text: "MEMORY", x: 210, y: 165, text_color: 0xAAAAAA, text_font: font1 }

    - id: page_skynas
      bg_color: 0x121212
      widgets:
        - label: { text: "SkyNAS STATUS", align: TOP_MID, y: 15, text_color: 0x2196F3 }
        - arc: { id: nas_cpu_gauge, x: 40, y: 55, width: 90, height: 90, arc_color: 0xF3212D }
        - label: { id: nas_cpu_val_label, x: 68, y: 145, text: "--%", text_color: 0x2196F3 }
        - label: { text: "CPU USAGE", x: 55, y: 165, text_color: 0xAAAAAA, text_font: font1 }
        - arc: { id: nas_mem_gauge, x: 190, y: 55, width: 90, height: 90, arc_color: 0xF3212D }
        - label: { id: nas_mem_val_label, x: 215, y: 145, text: "--%", text_color: 0x2196F3 }
        - label: { text: "MEMORY", x: 210, y: 165, text_color: 0xAAAAAA, text_font: font1 }

    - id: page_rack
      bg_color: 0x121212
      widgets:
        - label: { text: "RACK STATUS", align: TOP_MID, y: 15, text_color: 0x2196F3 }
        - arc: { id: temp_gauge, x: 40, y: 55, width: 90, height: 90, arc_color: 0xF3212D }
        - label: { id: temp_val_label, x: 68, y: 145, text: "--.-°C", text_color: 0x2196F3 }
        - label: { text: "TEMP", x: 68, y: 165, text_color: 0xAAAAAA, text_font: font1 }
        - arc: { id: hum_gauge, x: 190, y: 55, width: 90, height: 90, arc_color: 0xF3212D }
        - label: { id: hum_val_label, x: 215, y: 145, text: "--%", text_color: 0x2196F3 }
        - label: { text: "HUMIDITY", x: 205, y: 165, text_color: 0xAAAAAA, text_font: font1 }
    - id: page_fan
      bg_color: 0x121212
      widgets:
        - label: { text: "RACK FAN SYSTEM", align: TOP_MID, y: 10, text_color: 0x2196F3 }
        - label: { id: fan_speed_text, text: "SPEED: 0%", align: CENTER, y: 45, text_font: font2, text_color: 0xFFFFFF }
        - label: { id: rpm_display, text: "0 RPM", align: CENTER, y: 75, text_color: 0xAAAAAA }
        - button:
            x: 10
            y: 108
            width: 40
            height: 30
            bg_color: 0x222222
            radius: 4
            widgets:
            - label: { text: "-", align: CENTER, text_font: font2 }
            on_click:
              then:
                - lambda: |-
                    // id() already returns the pointer, no .obj needed
                    auto* slider = id(fan_slider);
                    auto* label = id(fan_speed_text);
                    
                    int current = lv_slider_get_value(slider);
                    int new_val = std::max(0, current - 10);
                    
                    // Update UI
                    lv_slider_set_value(slider, new_val, LV_ANIM_ON);
                    std::string text_str = "SPEED: " + std::to_string(new_val) + "%";
                    lv_label_set_text(label, text_str.c_str());
                    
                    // Update Fan Hardware
                    auto call = id(rack_fans).make_call();
                    call.set_speed(new_val);
                    call.perform();

        - slider:
            id: fan_slider
            x: 60
            y: 115
            width: 200
            height: 15
            min_value: 0
            max_value: 100
            bg_color: 0x333333
            indicator:
              bg_color: 0x2196F3
            knob:
              bg_color: 0xFFFFFF
            on_value:
              then:
                - fan.turn_on:
                    id: rack_fans
                    speed: !lambda "return (int)x;"
                - lvgl.label.update:
                    id: fan_speed_text
                    text: !lambda |-
                      static std::string buf;
                      buf = "SPEED: " + std::to_string((int)x) + "%";
                      return buf.c_str(); // This converts C++ string to const char*
        - button:
            x: 270
            y: 108
            width: 40
            height: 30
            bg_color: 0x222222
            radius: 4
            widgets:
            - label: { text: "+", align: CENTER, text_font: font2 }
            on_click:
              then:
                - lambda: |-
                    int current = lv_slider_get_value(id(fan_slider));
                    int new_val = std::min(100, current + 10);
                    
                    // Update UI
                    lv_slider_set_value(id(fan_slider), new_val, LV_ANIM_ON);
                    
                    // We use a static string here to prevent the "garbage text" bug
                    static std::string button_buf;
                    button_buf = "SPEED: " + std::to_string(new_val) + "%";
                    lv_label_set_text(id(fan_speed_text), button_buf.c_str());
                    
                    // Update Fan
                    auto call = id(rack_fans).make_call();
                    call.set_speed(new_val);
                    call.perform();
        - button:
            x: 110
            y: 205
            width: 100
            height: 30
            bg_color: 0x440000
            radius: 8
            widgets: [{label: {text: "STOP FANS", align: CENTER}}]
            on_click:
              then:
                - fan.turn_off: rack_fans
                - lvgl.slider.update: { id: fan_slider, value: 0 }
                - lvgl.label.update: { id: fan_speed_text, text: "SPEED: 0%" }

sensor:
  - platform: homeassistant
    entity_id: sensor.system_monitor_processor_use
    id: ha_cpu_usage
    on_value:
      then:
        - lvgl.arc.update: { id: ha_cpu_gauge, value: !lambda "return (int)x;" }
        - lvgl.label.update: 
            id: ha_cpu_val_label
            text: !lambda "return str_sprintf(\"%.1f%%\", x);"
        # Toggle label color based on usage
        - lambda: |-
            lv_obj_set_style_text_color(id(ha_cpu_val_label), 
              x > 90 ? lv_color_hex(0xFF0000) : lv_color_hex(0x2196F3), LV_PART_MAIN);
  - platform: homeassistant
    entity_id: sensor.system_monitor_memory_usage
    id: ha_memory_usage
    on_value:
      then:
        - lvgl.arc.update: { id: ha_mem_gauge, value: !lambda "return (int)x;" }
        - lvgl.label.update: 
            id: ha_mem_val_label
            text: !lambda "return str_sprintf(\"%.1f%%\", x);"
        - lambda: |-
            lv_obj_set_style_text_color(id(ha_mem_val_label), 
              x > 90 ? lv_color_hex(0xFF0000) : lv_color_hex(0x2196F3), LV_PART_MAIN);

  - platform: homeassistant
    entity_id: sensor.skynas_cpu_utilization_total
    id: nas_cpu_usage
    on_value:
      then:
        - lvgl.arc.update: { id: nas_cpu_gauge, value: !lambda "return (int)x;" }
        - lvgl.label.update: 
            id: nas_cpu_val_label
            text: !lambda "return str_sprintf(\"%.1f%%\", x);"
        # Toggle label color based on usage
        - lambda: |-
            lv_obj_set_style_text_color(id(nas_cpu_val_label), 
              x > 90 ? lv_color_hex(0xFF0000) : lv_color_hex(0x2196F3), LV_PART_MAIN);

  - platform: homeassistant
    entity_id: sensor.skynas_memory_usage_real
    id: nas_memory_usage
    on_value:
      then:
        - lvgl.arc.update: { id: nas_mem_gauge, value: !lambda "return (int)x;" }
        - lvgl.label.update: 
            id: nas_mem_val_label
            text: !lambda "return str_sprintf(\"%.1f%%\", x);"
        - lambda: |-
            lv_obj_set_style_text_color(id(nas_mem_val_label), 
              x > 90 ? lv_color_hex(0xFF0000) : lv_color_hex(0x2196F3), LV_PART_MAIN);

  - platform: homeassistant
    entity_id: sensor.senzor_rack_temperature
    id: rack_temperature
    on_value:
      then:
        - lvgl.arc.update: { id: temp_gauge, value: !lambda "return (int)x;" }
        - lvgl.label.update: { id: temp_val_label, text: !lambda "return str_sprintf(\"%.1f°C\", x);" }

  - platform: homeassistant
    entity_id: sensor.senzor_rack_humidity
    id: rack_humidity
    on_value:
      then:
        - lvgl.arc.update: { id: hum_gauge, value: !lambda "return (int)x;" }
        - lvgl.label.update: { id: hum_val_label, text: !lambda "return str_sprintf(\"%.1f%%\", x);" }

  - platform: uptime
    id: uptime_sensor
    update_interval: 60s
    on_value:
      then:
        - lvgl.label.update:
            id: uptime_label
            text: !lambda |-
              int ts = (int)x;
              int h = (ts % 86400) / 3600;
              int m = (ts % 3600) / 60;
              return str_sprintf("UPTIME: %dh %dm", h, m);

  - platform: pulse_counter
    pin: 
      number: GPIO22  # Common for fans on CYD, use a logic level shifter if fan is 12V!
      mode: INPUT_PULLUP
    name: "Rack Fan RPM"
    id: rack_fan_rpm
    update_interval: 5s
    filters:
      - multiply: 0.5 # Most fans pulse twice per revolution
    accuracy_decimals: 0
    unit_of_measurement: RPM
    on_value:
      then:
        - lvgl.label.update:
            id: rpm_display
            text: !lambda |-
              static std::string rpm_buf;
              rpm_buf = std::to_string((int)x) + " RPM";
              return rpm_buf.c_str();

  - platform: wifi_signal
    id: wifi_rssi
    update_interval: 10s
    on_value:
      then:
        - lambda: |-
            lv_color_t green = lv_color_hex(0x27AE60);
            lv_color_t grey  = lv_color_hex(0x444444);
            float s = x; 

            // Force opacity and color for each bar
            auto update_bar = [&](lv_obj_t* bar, bool active) {
                lv_obj_set_style_bg_opa(bar, LV_OPA_COVER, LV_PART_MAIN);
                lv_obj_set_style_bg_color(bar, active ? green : grey, LV_PART_MAIN);
            };

            update_bar(id(bar_1), s > -90);
            update_bar(id(bar_2), s > -80);
            update_bar(id(bar_3), s > -70);
            update_bar(id(bar_4), s > -60);